# Change these first
owner: tsolenthaler # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: tso.ch
    url: https://tso.ch
  - name: contentdesk.io
    url: https://contentdesk.io
  - name: thurgau-bodensee.ch
    url: https://thurgau-bodensee.ch
  - name: hosting.tso.ch
    check: "tcp-ping"
    url: 46.231.200.190
    port: 80
  - name: mc21a2202.dnh.net
    check: "tcp-ping"
    url: 185.46.59.81
    port: 80
  - name: ziggy.pim.tso.ch
    url: https://ziggy.pim.tso.ch
  - name: test.pim.tso.ch
    url: https://test.pim.tso.ch
  - name: ost.pim.tso.ch
    url: https://ost.pim.tso.ch
  - name: tgt.pim.tso.ch
    url: https://tgt.pim.tso.ch
  - name: hlt.pim.tso.ch
    url: https://hlt.pim.tso.ch
  - name: alar.pim.tso.ch
    url: https://alar.pim.tso.ch
  - name: Exoscale S3 Storage - Ziggy
    url: https://sos-ch-dk-2.exo.io/ziggypimtsoch/catalog/f/b/8/b/fb8b6445a2f864ac4532703d8ce8941d9233f814_Stiftsbibliothek_St._Gallen_1.jpg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://tso.ch/assets/images/j/TSO_Logo-zkcz1ye4dqz9yna.svg
  name: Status Page
  introTitle: "Status der Systeme"
  introMessage: "Dies ist ein Test."
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)!!!!